CREATE TABLE task2submissions(
  id int NOT NULL AUTO_INCREMENT,
  id_video INT NOT NULL,
  id_legenda INT NOT NULL,
  tinicial TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  tfinal TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  fingerprint VARCHAR(200) NOT NULL,
  PRIMARY KEY (id)
);
